### ISSUE TITLE
Server crashes on start

### ISSUE THREAD

**Issue by ThatFinnDev** [konsti219/astro-starter#3]
I've installed astro-starter on Ubuntu 22.10, but every time i start it the servers quits with code 2. I've tried reinstalling everything twice but it made no difference. 
Console:
[INFO] astro-starter v1.0.2
[INFO] work dir: /home/thatfinn/AstroneerServer
[INFO] Fetching public data...
[INFO] Latest server version: 1.26.128.0
[INFO] Public IP: **CENSORED**
[INFO] Webserver listening on localhost:5000
[INFO] Server processes starting...
[WARN] Playfab server query failed
[INFO - Server 1] Starting server
[INFO - Server 1] Starting Server process
[INFO - Server 1] Server process has quit, code: 2

And my starter.json is:
{
    "webserverPort": 5000,
    "owner": "ThatFinn",
    "servers": [
        {
            "id": "server1",
            "type": "local",
            "name": "Server 1",
            "IP": "_public",
            "port": 16500,
            "consolePort": "_auto",
            "consolePassword": "_random",
            "serverPassword": "",
            "whitelist": false,
            "maxPlayers": 8,
            "afkTimeout": 0,
            "saveInterval": 900,
            "backupSaves": true,
            "backupInterval": 3600,
            "enableAstrochatIntegration": false,
            "customHeartbeat": true,
            "discordWebhook": "",
            "restartAt": "06:00",
            "makeBackupSaveAt": "06:00",
            "backupIntervalHours": 24,
            "restoreSaveName": ""
        }
    ]
}

**Comment by konsti219** [comment]
You cannot host servers on Linux.
