### ISSUE TITLE
Crash in initial setup

### ISSUE THREAD

**Issue by merlin3of5** [konsti219/astro-starter#4]
When trying to run the initial setup, I am getting the below crash. 
Server is a fresh install of 2016.

C:\Program Files\astoneerserver>"./astro-starter.exe"

[INFO] astro-starter v1.0.2
[INFO] work dir: C:\Program Files\astoneerserver
[INFO] Fetching public data...
[INFO] Latest server version: 1.27.301.0
[INFO] Public IP: *removed*
[INFO] Downlaoding steamcmd...
[INFO] Downlaoding server files from steam...
[INFO] This will take a few minutes
error: NotFound: The system cannot find the file specified. (os error 2)
    at deno:core/core.js:86:46
    at unwrapOpResult (deno:core/core.js:106:13)
    at Object.opSync (deno:core/core.js:120:12)
    at opRun (deno:runtime/js/40_process.js:20:17)
    at Object.run (deno:runtime/js/40_process.js:104:17)
    at Starter.updateSteam (file://$deno$/bundle.js:14059:25)
    at async Starter.start (file://$deno$/bundle.js:13990:13)
    at async file://$deno$/bundle.js:14114:1

C:\Program Files\astoneerserver>pause
Press any key to continue . . .

**Comment by konsti219** [comment]
I don't maintain this tool anymore and can not even tell is going wrong. If you manage to fix it you can share your solution for others. But if you want to host an Astroneer server you should just use https://github.com/ricky-davis/AstroLauncher instead.
